require("core.plugin_config.gitsigns")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-lspconfig")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.nvim-treesitter")
require("core.plugin_config.telescope")
