#!/usr/bin/env bash

if ! command -v fzf > /dev/null 2>&1; then
  return
fi

if command -v pass > /dev/null 2>&1; then
  _fzf_complete_pass() {
    FZF_COMPLETION_TRIGGER="" _fzf_complete "-1" "${@}" < <(
      local PASS_DIR=${PASSWORD_STORE_DIR-${HOME}/.password-store}
      find "${PASS_DIR}" -name "*.gpg" -print | sed -e "s|${PASS_DIR}/\(.*\)\.gpg$|\1|"
    )
  }
  [[ -n "${BASH}" ]] && complete -F _fzf_complete_pass -o default -o bashdefault pass
fi

if command -v make > /dev/null 2>&1; then
  _fzf_complete_make() {
    # From https://unix.stackexchange.com/a/230050
    FZF_COMPLETION_TRIGGER="" _fzf_complete "-1" "${@}" < <(make -pqr 2> /dev/null | awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ {split($1,A,/ /);for(i in A)print A[i]}' | grep -v Makefile | sort -u)
  }
  [[ -n "${BASH}" ]] && complete -F _fzf_complete_make -o default -o bashdefault make
fi

if command -v psql > /dev/null 2>&1; then
  _fzf_complete_psql() {
    if [[ ! -f ${PGPASSFILE-${HOME}/.pgpass} ]]; then
      return
    fi

    FZF_COMPLETION_TRIGGER="" _fzf_complete "--ansi" "-1" "${@}" < <(
      local comment=""
      local RED='\033[0;31m'
      local GREEN='\033[0;32m'
      local BLUE='\033[0;34m'
      local YELLOW='\033[33m'
      local RESET='\033[0m'

      while IFS=":" read -r host port db user pass
      do
        if [[ ! ${host} =~ ^\s*# ]] && [[ ! ${host} =~ ^\s*$ ]]; then
          echo -e "host: ${BLUE}${host}${RESET} port: ${YELLOW}${port}${RESET} db: ${RED}${db}${RESET} user: ${GREEN}${user}${RESET} ${BLUE}${comment}${RESET}"
          comment=""
        elif [[ ${host} =~ ^\s*# ]]; then
          comment="${host}"
        fi
      done < "${PGPASSFILE-${HOME}/.pgpass}"
    )
  }

  _fzf_complete_psql_post() {
    sed -E 's|host: ([^:]*) port: ([^:]*) db: ([^:]*) user: ([^:]*)|\1 \2 \3 \4|g' | \
    awk '{if ($1 != "*") { print "-h " $1; } if ($2 != "*") { print "-p " $2; } if ($4 != "*") { print "-U " $4; } if ($3 != "*") { print $3; }}'
  }

  [[ -n "${BASH}" ]] && complete -F _fzf_complete_psql -o default -o bashdefault psql
fi
