#!/usr/bin/env bash

workon() {
  if [[ ! -e ${HOME}/.virtualenvs/${1} ]]; then
    echo "The virtualenv '${1}' does not exist"
    return
  fi

  if command -v deactivate > /dev/null 2>&1; then
    deactivate
  fi

  source "${HOME}/.virtualenvs/${1}/bin/activate"
}

_workon() {
  current="${COMP_WORDS[COMP_CWORD]}"
  virtualenvs=$(find "${HOME}/.virtualenvs/" -maxdepth 1 -mindepth 1 -type d -printf "%f\n")
  COMPREPLY=( $(compgen -W "$virtualenvs" -- "$current") )
  return 0
}
complete -F _workon workon

export MA_REPOSITORY="${HOME}/meilleursagents"
export MA_REPOSITORY_INFRA="${HOME}/MA-Infra"

if [[ -e "${MA_REPOSITORY}/tools/.bashrc" ]]; then
  source "${MA_REPOSITORY}/tools/.bashrc"
fi

if [[ -e "${MA_FOLDER}/MA-Infra/tools/gssh/gssh.sh" ]]; then
  source "${MA_FOLDER}/MA-Infra/tools/gssh/gssh.sh"
fi

if [[ -e "${MA_FOLDER}/docker/tools/docker.sh" ]]; then
  alias docker.sh="\${MA_FOLDER}/docker/tools/docker.sh"
fi

if [[ -e "${MA_FOLDER}/MA-Infra/tools/vault/vault.sh" ]]; then
  alias vault.sh="\${MA_FOLDER}/MA-Infra/tools/vault/vault.sh"
fi
