plugins=(pass)
CASE_SENSITIVE=true
ZSH_DISABLE_COMPFIX=true

ANTIGEN_PATH=$HOME/dotfiles
source $ANTIGEN_PATH/antigen/antigen.zsh
antigen init ${HOME}/.antigenrc
# Spaceships Prompt theme customization
export SPACESHIP_HOST_SHOW=false

export LANG=en
export TERM='xterm-256color'
export LC_ALL=en_US.utf-8
export LC_CTYPE=en_US.utf-8
export EDITOR=vi
export PGHOST=localhost

# Customize to your needs...
alias less='less -r'
alias vi='vim'
alias tmux='tmux -2'

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='
  --color fg:-1,bg:-1,hl:230,fg+:3,bg+:233,hl+:229
  --color info:150,prompt:110,spinner:150,pointer:167,marker:174
'
if command -v ag > /dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND="ag -l 2> /dev/null"
  export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
fi

# Load virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
if [ -f /usr/local/bin/virtualenvwrapper.sh ]
then
    source /usr/local/bin/virtualenvwrapper.sh
    workon
fi

if [ -f ~/.localrc ]
then
    source ~/.localrc
fi

PYTHONSTARTUP=~/.pythonrc.py
export PYTHONSTARTUP

# export PYENV_VERSION=system
# export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PATH="$HOME/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

alias fixssh='eval $(tmux showenv -s SSH_AUTH_SOCK)'
SSH_ENV="${HOME}/.ssh/environment"

stop_ssh_agent() {
  if [[ -n ${SSH_AGENT_PID:-} ]]; then
    ssh-agent -k
    rm -rf "${SSH_ENV}"
  fi
}

init_ssh_agent() {
  printf "Initializing new SSH agent...\n"

  touch "${SSH_ENV}"
  chmod 600 "${SSH_ENV}"

  ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  source "${SSH_ENV}" > /dev/null
}

start_ssh_agent() {
  stop_ssh_agent

  if [[ -d ${HOME}/.ssh/ ]]; then
    local AGENT_INITIALIZED="false"

    shopt -s nullglob
    for key in "${HOME}/.ssh/"*.pub; do
      if [[ ${AGENT_INITIALIZED} == "false" ]]; then
        AGENT_INITIALIZED="true"
        init_ssh_agent
      fi

      ssh-add -k "${key%.pub}"
    done
    shopt -u nullglob
  fi
}

if [[ -f ${SSH_ENV} ]]; then
  source "${SSH_ENV}" > /dev/null
else
  start_ssh_agent
fi

compdef _pass altpass
zstyle ':completion::complete:altpass::' prefix "$HOME/my_password_store"
altpass() {
  PASSWORD_STORE_DIR=$HOME/my_password_store pass $@
}

export PATH="/usr/local/sbin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/opt/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/opt/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/opt/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/opt/google-cloud-sdk/completion.zsh.inc"; fi

if ! command -v gcloud > /dev/null 2>&1; then
  return
fi

export BOTO_CONFIG=/dev/null
export CLOUDSDK_PYTHON=/usr/bin/python

gcloud_auth() {
  rm -rf "/tmp/${USER}*"
  gcloud auth login --no-launch-browser

  gcloud config unset compute/region
  gcloud config set project "$(gcloud projects list | grep dev | awk '{print $1}')"

  if command -v docker > /dev/null 2>&1; then
    gcloud --quiet auth configure-docker "eu.gcr.io"
  fi
}
