plugins=(pass)
CASE_SENSITIVE=true
ZSH_DISABLE_COMPFIX=true

ANTIGEN_PATH=$HOME/dotfiles
source $ANTIGEN_PATH/antigen/antigen.zsh
antigen init ${HOME}/.antigenrc

export LANG=en
export TERM='xterm-256color'
export LC_ALL=en_US.utf-8
export LC_CTYPE=en_US.utf-8
export EDITOR=vi
export PGHOST=localhost

# Customize to your needs...
alias less='less -r'
alias vi='vim'
alias tmux='tmux -2'

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='
  --color fg:-1,bg:-1,hl:230,fg+:3,bg+:233,hl+:229
  --color info:150,prompt:110,spinner:150,pointer:167,marker:174
'
if command -v ag > /dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND="ag -l 2> /dev/null"
  export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
fi

# Load virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
if [ -f /usr/local/bin/virtualenvwrapper.sh ]
then
    source /usr/local/bin/virtualenvwrapper.sh
    workon
fi

if [ -f ~/.localrc ]
then
    source ~/.localrc
fi

PYTHONSTARTUP=~/.pythonrc.py
export PYTHONSTARTUP

# export PYENV_VERSION=system
# export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PATH="$HOME/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

alias fixssh='eval $(tmux showenv -s SSH_AUTH_SOCK)'

compdef _pass altpass
zstyle ':completion::complete:altpass::' prefix "$HOME/my_password_store"
altpass() {
  PASSWORD_STORE_DIR=$HOME/my_password_store pass $@
}

export PATH="/usr/local/sbin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/stephanepoint/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/stephanepoint/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/stephanepoint/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/stephanepoint/google-cloud-sdk/completion.zsh.inc'; fi
