[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.fetch]
command = "uvx"
args = ["mcp-server-fetch"]

[mcp_servers.time]
command = "uvx"
args = ["mcp-server-time"]

[mcp_servers.Context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.notionApi]
command = "npx"
args = ["-y", "@notionhq/notion-mcp-server"]

[mcp_servers.aem-mcp]
command = "node"
args = ["/Users/spoint/dev/aem-mcp-server/dist/mcp-server.js"]
