theme = "nord"
default_agent = "plan"

[tools.bash]
allowlist = [
  "/Users/oinp/dotfiles/vibe/.vibe/*",
  "/Users/oinp/dotfiles/vibe/.vibe/plans/*",
  "cat",
  "find",
  "head",
  "ls",
  "mkdir",
  "touch",
  "xargs",
]

[[models]]
name = "mistral-large-latest"
provider = "mistral"
alias = "mistral-large"
thinking = "off"
