require("plugins.base")
require("plugins.code-enhancements")
require("plugins.colorscheme")
require("plugins.formatting")
require("plugins.lsp")
require("plugins.markdown")
require("plugins.treesitter")
require("plugins.ui")
